POST http://localhost:3000/addcosmetictype.test.php
Content-Type: application/x-www-form-urlencoded

cosmetic_type_id=1
&cosmetic_type_code=LIP
&cosmetic_shelf_number=B21
&cosmetic_type_name=Lipstick

###
GET http://localhost:3000/listcosmetictypes.test.php

###
POST http://localhost:3000/changecosmetictype.test.php
Content-Type: application/x-www-form-urlencoded

cosmetic_type_id=1
&cosmetic_type_code=LIP
&cosmetic_type_name=Lipstick
&cosmetic_shelf_number=A43

###
POST http://localhost:3000/removecosmetictype.test.php
Content-Type: application/x-www-form-urlencoded

cosmetic_type_id=1